"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,BookOpen,Brain,Check,ChevronRight,Clock,Library,Lightbulb,RotateCcw,Sparkles,Target} from "lucide-react";
import {chapters,Chapter} from "./data";

type View="library"|"book"|"chapter";
export default function Home(){
 const [view,setView]=useState<View>("library"); const [chapter,setChapter]=useState<Chapter>(chapters[0]); const [reveal,setReveal]=useState(false); const [done,setDone]=useState<number[]>([]);
 useEffect(()=>{const x=localStorage.getItem("bookwise-done");if(x)setDone(JSON.parse(x))},[]);
 const open=(c:Chapter)=>{setChapter(c);setReveal(false);setView("chapter");scrollTo(0,0)};
 const complete=()=>{const n=[...new Set([...done,chapter.id])];setDone(n);localStorage.setItem("bookwise-done",JSON.stringify(n));};
 if(view==="library")return <Shell><header className="pt-7 pb-8"><div className="flex items-center gap-2 text-sm font-semibold"><div className="grid h-8 w-8 place-items-center rounded-xl bg-[#26332b] text-white"><BookOpen size={17}/></div>BOOKWISE</div><div className="mt-10 text-xs font-semibold uppercase tracking-[.2em] text-[#71806b]">Your learning library</div><h1 className="serif mt-3 max-w-xl text-4xl leading-tight md:text-5xl">Books are only useful when their ideas stay with you.</h1><p className="mt-4 max-w-lg leading-7 text-[#78736a]">Turn what you read into simple ideas, useful examples and memories you can actually recall.</p></header><section><div className="mb-4 flex items-end justify-between"><div><h2 className="serif text-2xl">Continue learning</h2><p className="mt-1 text-sm text-[#78736a]">{done.length} of {chapters.length} prototype chapters mastered</p></div><Library size={20}/></div><button onClick={()=>setView("book")} className="group w-full overflow-hidden rounded-[28px] border border-[#e6e0d5] bg-[#fffdf8] text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="grid md:grid-cols-[210px_1fr]"><div className="flex min-h-52 items-end bg-[#24322b] p-7 text-[#f4efe4]"><div><div className="text-xs uppercase tracking-[.2em] opacity-60">Daniel Kahneman</div><div className="serif mt-3 text-3xl leading-tight">Thinking,<br/>Fast and Slow</div></div></div><div className="p-7 md:p-9"><span className="rounded-full bg-[#eef0e8] px-3 py-1 text-xs font-semibold text-[#64705f]">CURRENTLY LEARNING</span><h3 className="serif mt-5 text-2xl">Understand how your mind makes decisions.</h3><p className="mt-3 max-w-xl leading-7 text-[#78736a]">A practical learning path through intuition, attention, bias and judgment—without getting lost in technical detail.</p><div className="mt-7 h-1.5 overflow-hidden rounded-full bg-[#ebe6dc]"><div className="h-full bg-[#71806b]" style={{width:`${done.length/chapters.length*100}%`}}/></div><div className="mt-3 flex justify-between text-sm text-[#78736a]"><span>{Math.round(done.length/chapters.length*100)}% mastered</span><span className="flex items-center gap-1 font-semibold text-[#26332b]">Open book <ChevronRight size={16}/></span></div></div></div></button></section></Shell>;
 if(view==="book")return <Shell><Top back={()=>setView("library")}/><div className="py-8 md:py-12"><span className="text-xs font-semibold uppercase tracking-[.2em] text-[#71806b]">Book overview</span><h1 className="serif mt-3 text-4xl md:text-5xl">Thinking, Fast and Slow</h1><p className="mt-2 text-[#78736a]">Daniel Kahneman · Psychology & decision-making</p><div className="mt-8 rounded-3xl border border-[#e6e0d5] bg-[#fffdf8] p-6 md:p-8"><div className="flex gap-4"><Sparkles className="mt-1 shrink-0 text-[#71806b]" size={20}/><div><div className="text-sm font-bold">THE BOOK IN ONE IDEA</div><p className="serif mt-2 text-xl leading-8">Much of our thinking happens automatically. Learning when to trust intuition—and when to slow down—can improve our judgments and decisions.</p></div></div></div><div className="mt-10 flex items-end justify-between"><div><h2 className="serif text-2xl">Start with the ideas</h2><p className="mt-1 text-sm text-[#78736a]">Short lessons designed for understanding, not completion.</p></div><span className="text-sm text-[#78736a]">{done.length}/{chapters.length}</span></div><div className="mt-4 space-y-3">{chapters.map((c,i)=><button key={c.id} onClick={()=>open(c)} className="flex w-full items-center gap-4 rounded-2xl border border-[#e6e0d5] bg-[#fffdf8] p-4 text-left transition hover:bg-white md:p-5"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-full text-sm font-bold ${done.includes(c.id)?"bg-[#71806b] text-white":"bg-[#f0ece3]"}`}>{done.includes(c.id)?<Check size={17}/>:i+1}</div><div className="min-w-0 flex-1"><div className="font-semibold">{c.title}</div><div className="mt-1 text-sm text-[#8a8479]">{c.eyebrow} · 3 min</div></div><ChevronRight size={18} className="text-[#9a948a]"/></button>)}</div></div></Shell>;
 return <Shell><Top back={()=>setView("book")}/><article className="mx-auto max-w-2xl py-8 md:py-12"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-[#71806b]"><Clock size={14}/> 3 minute lesson</div><h1 className="serif mt-4 text-4xl leading-tight md:text-5xl">{chapter.title}</h1><p className="mt-3 text-lg text-[#78736a]">{chapter.eyebrow}</p><Card icon={<Brain/>} label="30-second summary"><p>{chapter.summary}</p></Card><Card icon={<Lightbulb/>} label="The big idea" accent><p className="serif text-2xl leading-9">{chapter.bigIdea}</p></Card><Card icon={<BookOpen/>} label="Simple example"><p>{chapter.example}</p></Card><Card icon={<Target/>} label="Put it in your world"><p>{chapter.lifeExample}</p></Card><div className="my-8 rounded-3xl bg-[#26332b] p-7 text-[#f7f4ed]"><div className="text-xs font-bold uppercase tracking-[.18em] opacity-60">Remember it like this</div><div className="serif mt-3 text-3xl">“{chapter.anchor}”</div></div><Card icon={<Sparkles/>} label="Use it tomorrow"><p>{chapter.apply}</p></Card><div className="mt-8 rounded-3xl border border-[#d9d3c8] bg-[#fffdf8] p-6 md:p-8"><div className="flex items-center gap-2 text-sm font-bold"><RotateCcw size={17}/> MAKE IT STICK</div><h3 className="serif mt-4 text-2xl leading-8">{chapter.question}</h3>{!reveal?<button onClick={()=>setReveal(true)} className="mt-6 w-full rounded-2xl bg-[#26332b] px-5 py-3.5 font-semibold text-white">Reveal answer</button>:<><div className="mt-5 rounded-2xl bg-[#f0eee7] p-5 leading-7">{chapter.answer}</div><button onClick={complete} className="mt-4 w-full rounded-2xl bg-[#71806b] px-5 py-3.5 font-semibold text-white">{done.includes(chapter.id)?"Mastered ✓":"I got it — mark as mastered"}</button></>}</div></article></Shell>
}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen"><div className="mx-auto max-w-5xl px-5 pb-20 md:px-8">{children}</div></main>}
function Top({back}:{back:()=>void}){return <div className="flex items-center justify-between border-b border-[#e6e0d5] py-5"><button onClick={back} className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={17}/> Back</button><div className="flex items-center gap-2 text-xs font-bold tracking-wider"><BookOpen size={16}/> BOOKWISE</div></div>}
function Card({icon,label,accent=false,children}:{icon:React.ReactNode,label:string,accent?:boolean,children:React.ReactNode}){return <section className={`mt-6 rounded-3xl border p-6 md:p-7 ${accent?"border-[#dce2d6] bg-[#eef0e8]":"border-[#e6e0d5] bg-[#fffdf8]"}`}><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#71806b]"><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span>{label}</div><div className="mt-4 text-[17px] leading-8">{children}</div></section>}
