"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,BookOpen,Brain,Check,ChevronRight,Clock,Library,Lightbulb,RotateCcw,Sparkles,Target,Search,Bookmark,Home as HomeIcon,BarChart3,Menu} from "lucide-react";
import {chapters,Chapter} from "./data";

type View="library"|"book"|"chapter";
export default function Home(){
 const [view,setView]=useState<View>("library"); const [chapter,setChapter]=useState<Chapter>(chapters[0]); const [reveal,setReveal]=useState(false); const [done,setDone]=useState<number[]>([]);
 useEffect(()=>{const x=localStorage.getItem("bookwise-done");if(x)setDone(JSON.parse(x))},[]);
 const open=(c:Chapter)=>{setChapter(c);setReveal(false);setView("chapter");scrollTo(0,0)};
 const complete=()=>{const n=Array.from(new Set([...done,chapter.id]));setDone(n);localStorage.setItem("bookwise-done",JSON.stringify(n));};
 const pct=Math.round(done.length/chapters.length*100);
 if(view==="library")return <Shell nav><header className="pt-6"><div className="flex items-center justify-between"><Brand/><div className="flex gap-3 text-[#132238]"><Search size={20}/><div className="h-7 w-7 rounded-full bg-[#e7ebf1]"/></div></div><div className="hero mt-7 overflow-hidden rounded-[24px] border border-[#e5e7eb] p-7 md:p-10"><div className="max-w-md"><h1 className="serif text-4xl leading-[1.05] md:text-5xl">Better Books.<br/>A Better You.</h1><p className="mt-4 max-w-xs text-[15px] leading-6 text-[#45536a]">Big ideas, simply explained.<br/>One chapter at a time.</p></div><div className="book-stack" aria-hidden="true"><span/><span/><span/></div></div></header><section className="mt-7 rounded-[22px] border border-[#e6e9ee] bg-white p-5 shadow-[0_8px_30px_rgba(18,34,56,.04)]"><div className="flex justify-between"><h2 className="serif text-xl">Your Reading Progress</h2><span className="text-sm font-semibold text-[#b98634]">{done.length} of {chapters.length} lessons</span></div><div className="mt-4 h-2 rounded-full bg-[#edf0f4]"><div className="h-full rounded-full bg-[#d8ad59]" style={{width:`${pct}%`}}/></div><div className="mt-5 grid grid-cols-3 divide-x divide-[#e6e9ee] text-center"><Stat n={done.length} t="Mastered"/><Stat n={chapters.length-done.length} t="To learn"/><Stat n={chapters.length} t="Lessons"/></div></section><section className="mt-8"><div className="flex items-center justify-between"><h2 className="serif text-2xl">Continue Reading</h2><button onClick={()=>setView("book")} className="text-sm text-[#526177]">View all →</button></div><button onClick={()=>setView("book")} className="mt-4 grid w-full grid-cols-[105px_1fr] gap-5 rounded-[22px] border border-[#e6e9ee] bg-white p-4 text-left shadow-[0_8px_30px_rgba(18,34,56,.04)] md:grid-cols-[125px_1fr]"><BookCover/><div className="flex min-w-0 flex-col justify-center"><h3 className="serif text-xl md:text-2xl">Thinking, Fast and Slow</h3><p className="mt-1 text-sm text-[#647187]">Daniel Kahneman</p><div className="mt-5 h-1.5 rounded-full bg-[#e9edf2]"><div className="h-full rounded-full bg-[#24486f]" style={{width:`${pct}%`}}/></div><div className="mt-2 text-xs text-[#647187]">{done.length} of {chapters.length} lessons mastered</div><span className="mt-4 inline-flex w-fit items-center gap-1 rounded-lg bg-[#132c49] px-4 py-2 text-sm font-semibold text-white">Continue <ChevronRight size={15}/></span></div></button></section><section className="mt-8 pb-6"><div className="flex justify-between"><h2 className="serif text-2xl">Your Library</h2><span className="text-sm text-[#647187]">View all →</span></div><div className="mt-4 flex gap-4 overflow-hidden"><MiniBook title="Thinking, Fast and Slow"/><MiniBook title="Atomic Habits" alt/><MiniBook title="The Psychology of Money" blue/></div></section></Shell>;
 if(view==="book")return <Shell nav><Top back={()=>setView("library")}/><div className="py-7 md:py-10"><div className="grid gap-7 md:grid-cols-[180px_1fr] md:items-center"><BookCover large/><div><h1 className="serif text-4xl leading-tight md:text-5xl">Thinking,<br className="hidden md:block"/> Fast and Slow</h1><p className="mt-2 text-lg text-[#536177]">Daniel Kahneman</p><div className="mt-4 flex flex-wrap gap-2"><Tag>Psychology</Tag><Tag>Decision Making</Tag><Tag>Behaviour</Tag></div><button onClick={()=>open(chapters.find(c=>!done.includes(c.id))||chapters[0])} className="mt-6 w-full rounded-xl bg-[#132c49] px-5 py-3.5 font-semibold text-white md:w-auto md:min-w-64">▶ &nbsp; Continue Learning</button></div></div><div className="mt-8 grid grid-cols-3 divide-x rounded-2xl border border-[#e6e9ee] bg-white py-4 text-center"><Stat n={chapters.length} t="Lessons"/><Stat n="3 min" t="Each"/><Stat n={pct+"%"} t="Mastered"/></div><div className="mt-8 border-b border-[#dfe4ea]"><div className="flex gap-8"><span className="border-b-2 border-[#132c49] pb-3 text-sm font-bold">Overview</span><button className="pb-3 text-sm text-[#66748a]" onClick={()=>document.getElementById("chapters")?.scrollIntoView({behavior:"smooth"})}>Chapters</button><span className="pb-3 text-sm text-[#66748a]">Notes</span></div></div><section className="py-7"><h2 className="serif text-2xl">About this book</h2><p className="mt-3 max-w-2xl leading-7 text-[#46546a]">A practical exploration of how intuitive and deliberate thinking shape everyday judgments. Bookwise turns the core concepts into short lessons you can understand, apply and remember.</p><div className="mt-6 rounded-2xl bg-[#edf4fb] p-5"><h3 className="serif text-xl">What you’ll take away</h3><div className="mt-4 space-y-3 text-sm leading-6 text-[#3f5067]"><Take>Know when fast intuition helps—and when to slow down.</Take><Take>Spot common shortcuts that distort decisions.</Take><Take>Build a habit of checking important judgments.</Take></div></div></section><section id="chapters" className="pt-2"><h2 className="serif text-2xl">Chapters</h2><div className="mt-4 divide-y divide-[#e3e7ec] border-y border-[#e3e7ec]">{chapters.map((c,i)=><button key={c.id} onClick={()=>open(c)} className="flex w-full items-center gap-4 py-4 text-left"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-full border text-sm font-semibold ${done.includes(c.id)?"border-[#55b6a7] bg-[#55b6a7] text-white":"border-[#d8dee6] bg-white"}`}>{done.includes(c.id)?<Check size={16}/>:i+1}</div><div className="flex-1"><div className="serif text-lg">{c.title}</div><div className="mt-0.5 text-sm text-[#778398]">{c.eyebrow}</div></div><ChevronRight size={17} className="text-[#a2abb8]"/></button>)}</div></section></div></Shell>;
 return <Shell><Top back={()=>setView("book")} title={`Chapter ${chapter.id}`}/><article className="mx-auto max-w-2xl py-8 md:py-12"><div className="text-center text-xs font-semibold uppercase tracking-[.15em] text-[#728096]">{chapter.id} of {chapters.length} · 3 minute lesson</div><h1 className="serif mt-5 text-center text-4xl leading-tight md:text-5xl">{chapter.title}</h1><p className="mt-2 text-center text-lg text-[#657389]">{chapter.eyebrow}</p><div className="mt-8 rounded-[22px] bg-[#edf4fb] p-6"><div className="flex gap-3"><span className="serif text-4xl leading-none text-[#2b5f93]">“</span><p className="serif text-xl leading-8">{chapter.bigIdea}</p></div></div><p className="mt-7 text-[17px] leading-8 text-[#35445a]">{chapter.summary}</p><ReaderCard icon={<Lightbulb/>} label="Key Example" warm><p>{chapter.example}</p></ReaderCard><ReaderCard icon={<Target/>} label="Real Life Application"><p>{chapter.lifeExample}</p></ReaderCard><div className="my-7 border-l-2 border-[#132c49] py-2 pl-5"><div className="text-xs font-bold uppercase tracking-[.14em] text-[#7b8798]">Remember it like this</div><div className="serif mt-2 text-2xl">“{chapter.anchor}”</div></div><ReaderCard icon={<Sparkles/>} label="Use it tomorrow"><p>{chapter.apply}</p></ReaderCard><div className="mt-8 rounded-[22px] border border-[#dfe4ea] bg-white p-6"><div className="flex items-center gap-2 text-sm font-bold text-[#132c49]"><RotateCcw size={17}/> MAKE IT STICK</div><h3 className="serif mt-4 text-2xl leading-8">{chapter.question}</h3>{!reveal?<button onClick={()=>setReveal(true)} className="mt-6 w-full rounded-xl bg-[#132c49] px-5 py-3.5 font-semibold text-white">Show what I should remember →</button>:<><div className="mt-5 rounded-xl bg-[#f3f6f9] p-5 leading-7 text-[#405069]">{chapter.answer}</div><button onClick={complete} className="mt-4 w-full rounded-xl bg-[#2e7f76] px-5 py-3.5 font-semibold text-white">{done.includes(chapter.id)?"Mastered ✓":"I got it — mark as mastered"}</button></>}</div></article></Shell>
}
function Shell({children,nav=false}:{children:React.ReactNode,nav?:boolean}){return <main className="min-h-screen bg-[#fbfbfa] text-[#122238]"><div className={`mx-auto max-w-5xl px-5 md:px-8 ${nav?"pb-24":"pb-16"}`}>{children}</div>{nav&&<BottomNav/>}</main>}
function Brand(){return <div className="flex items-center gap-2"><BookOpen size={27} className="text-[#64758a]"/><div><div className="serif text-2xl font-bold">Bookwise</div><div className="text-[9px] tracking-[.08em] text-[#66748a]">READ · UNDERSTAND · REMEMBER</div></div></div>}
function Top({back,title}:{back:()=>void,title?:string}){return <div className="flex items-center justify-between border-b border-[#e6e9ee] py-5"><button onClick={back}><ArrowLeft size={20}/></button>{title?<div className="serif text-lg font-bold">{title}</div>:<Brand/>}<div className="flex gap-3"><Bookmark size={18}/><span className="font-bold">•••</span></div></div>}
function BottomNav(){return <nav className="fixed inset-x-0 bottom-0 z-10 border-t border-[#e2e6eb] bg-white/95 backdrop-blur"><div className="mx-auto grid max-w-xl grid-cols-4 py-2 text-center text-[10px] text-[#617087]"><div className="flex flex-col items-center gap-1 font-bold text-[#132c49]"><HomeIcon size={20}/>Home</div><div className="flex flex-col items-center gap-1"><Library size={20}/>Library</div><div className="flex flex-col items-center gap-1"><BarChart3 size={20}/>Progress</div><div className="flex flex-col items-center gap-1"><Menu size={20}/>More</div></div></nav>}
function BookCover({large=false}:{large?:boolean}){return <div className={`book-cover shrink-0 rounded-lg border border-[#dedbd3] bg-[#f7f1e6] shadow-[0_8px_18px_rgba(25,35,50,.12)] ${large?"h-[245px] w-[170px]":"h-[160px] w-[105px]"}`}><div className="text-[7px] tracking-[.2em]">THINKING,</div><div className="mt-2 serif text-[13px] tracking-[.08em]">FAST AND SLOW</div><div className="my-auto h-[3px] w-12 rounded bg-[#c56e32]"/><div className="text-[7px] tracking-[.22em]">DANIEL KAHNEMAN</div></div>}
function MiniBook({title,alt=false,blue=false}:{title:string,alt?:boolean,blue?:boolean}){return <div className={`flex h-40 w-28 shrink-0 items-center justify-center rounded-lg border p-3 text-center shadow-sm ${alt?"bg-[#efe2cf]":blue?"bg-[#e6f0ec]":"bg-[#f7f1e6]"}`}><span className="serif text-base leading-5">{title}</span></div>}
function Stat({n,t}:{n:string|number,t:string}){return <div><div className="serif text-xl font-bold">{n}</div><div className="mt-1 text-xs text-[#6e7a8c]">{t}</div></div>}
function Tag({children}:{children:React.ReactNode}){return <span className="rounded-full bg-[#edf1f5] px-3 py-1.5 text-xs text-[#516077]">{children}</span>}
function Take({children}:{children:React.ReactNode}){return <div className="flex gap-3"><Check size={17} className="mt-1 shrink-0 text-[#3575ad]"/><span>{children}</span></div>}
function ReaderCard({icon,label,warm=false,children}:{icon:React.ReactNode,label:string,warm?:boolean,children:React.ReactNode}){return <section className={`mt-6 rounded-[20px] p-6 ${warm?"bg-[#fff4df]":"border border-[#e2e6eb] bg-white"}`}><div className={`flex items-center gap-2 text-sm font-bold ${warm?"text-[#a86b19]":"text-[#132c49]"}`}><span className="[&>svg]:h-5 [&>svg]:w-5">{icon}</span>{label}</div><div className="mt-3 text-[16px] leading-7 text-[#405069]">{children}</div></section>}
